// Build the Stargaze courtyard-view panorama assets + manifest.
//
// Source: a "Tower 2 Rivali" folder of <Floor>/Apartment/<apt>/ directories,
// each holding several drone frames plus one wide "*_stitch.jpg" panorama.
// Apartment numbers are floor*100 + position (e.g. 30th floor, position 2 ->
// 3002), and the position (1-6) is the floor-plan svg number.
//
// For every apartment folder with a usable stitch we:
//   1. pick the right stitch (see selectStitch),
//   2. re-encode it FROM SOURCE to a TARGET_H-tall WebP (high quality, no
//      double-compression) at public/unit/views/<apt>.webp,
//   3. record <apt> in the generated manifest (src/data/stargazeViews.js).
//
// "Sold out" apartments (no stitch, or only a misplaced neighbour's stitch) are
// omitted, so they never appear in the floor dropdown or on the floor plan.
//
// Usage: node scripts/build-views.mjs ["/path/to/Tower 2 Rivali"]
import sharp from 'sharp'
import { readdirSync, statSync, rmSync, mkdirSync, writeFileSync } from 'fs'
import { join, dirname, basename } from 'path'
import { fileURLToPath } from 'url'

const HERE = dirname(fileURLToPath(import.meta.url))
const ROOT = dirname(HERE)
const DEFAULT_SRC = '/Users/Arsalan/Downloads/rivali/Tower 2 Rivali'
const OUT_DIR = join(ROOT, 'public', 'unit', 'views')
const MANIFEST = join(ROOT, 'src', 'data', 'stargazeViews.js')
const TARGET_H = 1440 // output height in px (full-screen panorama)
const WEBP_QUALITY = 85 // high quality, re-encoded from the original source

const APT_RE = /(?:Apt[_ ]+|_)(\d{3,4})_stitch/i

// Apartment number named inside a stitch filename, or null if generic.
const parseApt = (filename) => {
  const m = filename.match(APT_RE)
  return m ? Number(m[1]) : null
}

// Choose the stitch that genuinely belongs to `apt`: prefer a name match, else
// a generically named stitch simply sitting in this folder, else null (the only
// stitch(es) name a different apartment — a misplaced neighbour file, so the
// apartment is treated as sold out).
const selectStitch = (apt, stitches) => {
  const sorted = [...stitches].sort()
  const matched = sorted.filter((f) => parseApt(f) === apt)
  if (matched.length) return matched[0]
  const generic = sorted.filter((f) => parseApt(f) === null)
  return generic.length ? generic[0] : null
}

const main = async () => {
  const src = process.argv[2] || DEFAULT_SRC
  if (!statSync(src, { throwIfNoEntry: false })?.isDirectory()) {
    console.error(`Source folder not found: ${src}`)
    process.exit(1)
  }

  // Fresh output dir (drop any earlier .jpg/.webp renders).
  rmSync(OUT_DIR, { recursive: true, force: true })
  mkdirSync(OUT_DIR, { recursive: true })

  const available = []
  const skipped = []

  for (const floorDir of readdirSync(src).sort()) {
    const aptRoot = join(src, floorDir, 'Apartment')
    if (!statSync(aptRoot, { throwIfNoEntry: false })?.isDirectory()) continue
    for (const aptName of readdirSync(aptRoot).sort()) {
      const aptPath = join(aptRoot, aptName)
      if (!/^\d+$/.test(aptName)) continue
      if (!statSync(aptPath).isDirectory()) continue
      const apt = Number(aptName)
      const stitches = readdirSync(aptPath).filter(
        (f) => /\.jpg$/i.test(f) && /stitch/i.test(f),
      )
      if (!stitches.length) {
        skipped.push([apt, 'no stitch (sold out)'])
        continue
      }
      const chosen = selectStitch(apt, stitches)
      if (!chosen) {
        skipped.push([apt, `only misplaced stitch(es): ${stitches.sort().join(', ')}`])
        continue
      }
      await sharp(join(aptPath, chosen))
        .resize({ height: TARGET_H, withoutEnlargement: true, kernel: 'lanczos3' })
        .webp({ quality: WEBP_QUALITY })
        .toFile(join(OUT_DIR, `${apt}.webp`))
      available.push(apt)
      console.log(`  ${apt}  <-  ${chosen}`)
    }
  }

  available.sort((a, b) => a - b)
  writeManifest(available)

  console.log(`\nWrote ${available.length} panoramas (WebP q${WEBP_QUALITY}) to ${OUT_DIR}`)
  console.log(`Manifest: ${MANIFEST}`)
  if (skipped.length) {
    console.log(`\nSkipped ${skipped.length} apartment(s):`)
    skipped
      .sort((a, b) => a[0] - b[0])
      .forEach(([apt, why]) => console.log(`  ${apt}: ${why}`))
  }
}

const writeManifest = (available) => {
  const apts = available.join(', ')
  const body =
    `// AUTO-GENERATED by scripts/build-views.mjs — do not edit by hand.\n` +
    `// Stargaze apartments (floor*100 + svg-position) that have a courtyard\n` +
    `// panorama. Sold-out apartments are absent, so they're hidden from the\n` +
    `// floor dropdown in the courtyard view.\n` +
    `export const STARGAZE_VIEW_APTS = [${apts}]\n\n` +
    `const VIEW_SET = new Set(STARGAZE_VIEW_APTS)\n\n` +
    `// Apartment number for a floor (1-39) + svg position (1-6).\n` +
    `export const aptNumber = (floor, position) => floor * 100 + position\n\n` +
    `// Public path to a panorama, or null when that apartment is sold out.\n` +
    `export const viewImage = (floor, position) =>\n` +
    `  VIEW_SET.has(aptNumber(floor, position))\n` +
    `    ? \`/unit/views/\${aptNumber(floor, position)}.webp\`\n` +
    `    : null\n\n` +
    `// Floors (ascending) where the given svg position has a panorama.\n` +
    `export const floorsForPosition = (position) =>\n` +
    `  STARGAZE_VIEW_APTS.filter((a) => a % 100 === position).map((a) =>\n` +
    `    Math.floor(a / 100),\n` +
    `  )\n`
  mkdirSync(dirname(MANIFEST), { recursive: true })
  writeFileSync(MANIFEST, body)
}

main()
