#!/usr/bin/env python3
"""Build the Stargaze courtyard-view panorama assets + manifest.

Source: a "Tower 2 Rivali" folder of <Floor>/Apartment/<apt>/ directories, each
holding several drone frames plus one wide "*_stitch.jpg" panorama. Apartment
numbers are floor*100 + position (e.g. 30th floor, position 2 -> 3002), and the
position (1-6) is the floor-plan svg number.

For every apartment folder that has a usable stitch we:
  1. pick the right stitch (see select_stitch),
  2. downscale it to <= TARGET_H px tall JPEG into public/unit/views/<apt>.jpg,
  3. record <apt> in the generated manifest (src/data/stargazeViews.js).

"Sold out" apartments (no stitch, or only a misplaced neighbour's stitch) are
omitted, so they never appear in the floor dropdown or on the floor plan.

Usage: python3 scripts/build-views.py ["/path/to/Tower 2 Rivali"]
"""
import os
import re
import subprocess
import sys

DEFAULT_SRC = "/Users/Arsalan/Downloads/rivali/Tower 2 Rivali"
HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
OUT_DIR = os.path.join(ROOT, "public", "unit", "views")
MANIFEST = os.path.join(ROOT, "src", "data", "stargazeViews.js")
TARGET_H = 1440          # output height in px (full-screen panorama)
JPEG_QUALITY = 70

APT_RE = re.compile(r"(?:Apt[_ ]+|_)(\d{3,4})_stitch", re.IGNORECASE)


def parse_apt(filename):
    """Apartment number named inside a stitch filename, or None if generic."""
    m = APT_RE.search(filename)
    return int(m.group(1)) if m else None


def select_stitch(apt, stitches):
    """Choose the stitch that genuinely belongs to `apt`.

    Prefer a file whose name matches the apartment number; else a generically
    named stitch (no apt number in the name) that's simply sitting in this
    folder; else None -- the only stitch(es) name a *different* apartment, so
    this is a misplaced neighbour file and the apartment is treated as sold out.
    """
    stitches = sorted(stitches)
    matched = [f for f in stitches if parse_apt(f) == apt]
    if matched:
        return matched[0]
    generic = [f for f in stitches if parse_apt(f) is None]
    if generic:
        return generic[0]
    return None


def main():
    src = sys.argv[1] if len(sys.argv) > 1 else DEFAULT_SRC
    if not os.path.isdir(src):
        sys.exit(f"Source folder not found: {src}")

    os.makedirs(OUT_DIR, exist_ok=True)

    available = []   # apt numbers we produced an image for
    skipped = []     # (apt, reason)

    for floor_dir in sorted(os.listdir(src)):
        apt_root = os.path.join(src, floor_dir, "Apartment")
        if not os.path.isdir(apt_root):
            continue
        for apt_name in sorted(os.listdir(apt_root)):
            apt_path = os.path.join(apt_root, apt_name)
            if not os.path.isdir(apt_path) or not apt_name.isdigit():
                continue
            apt = int(apt_name)
            stitches = [
                f for f in os.listdir(apt_path)
                if f.lower().endswith(".jpg") and "stitch" in f.lower()
            ]
            if not stitches:
                skipped.append((apt, "no stitch (sold out)"))
                continue
            chosen = select_stitch(apt, stitches)
            if chosen is None:
                named = ", ".join(sorted(stitches))
                skipped.append((apt, f"only misplaced stitch(es): {named}"))
                continue

            in_path = os.path.join(apt_path, chosen)
            out_path = os.path.join(OUT_DIR, f"{apt}.jpg")
            subprocess.run(
                ["sips", "--resampleHeight", str(TARGET_H),
                 "-s", "format", "jpeg",
                 "-s", "formatOptions", str(JPEG_QUALITY),
                 in_path, "-o", out_path],
                check=True, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL,
            )
            available.append(apt)
            print(f"  {apt}  <-  {chosen}")

    available.sort()
    write_manifest(available)

    print(f"\nWrote {len(available)} panoramas to {OUT_DIR}")
    print(f"Manifest: {MANIFEST}")
    if skipped:
        print(f"\nSkipped {len(skipped)} apartment(s):")
        for apt, why in sorted(skipped):
            print(f"  {apt}: {why}")


def write_manifest(available):
    apts = ", ".join(str(a) for a in available)
    body = (
        "// AUTO-GENERATED by scripts/build-views.py — do not edit by hand.\n"
        "// Stargaze apartments (floor*100 + svg-position) that have a courtyard\n"
        "// panorama. Sold-out apartments are absent, so they're hidden from the\n"
        "// floor dropdown in the courtyard view.\n"
        f"export const STARGAZE_VIEW_APTS = [{apts}]\n\n"
        "const VIEW_SET = new Set(STARGAZE_VIEW_APTS)\n\n"
        "// Apartment number for a floor (1-39) + svg position (1-6).\n"
        "export const aptNumber = (floor, position) => floor * 100 + position\n\n"
        "// Public path to a panorama, or null when that apartment is sold out.\n"
        "export const viewImage = (floor, position) =>\n"
        "  VIEW_SET.has(aptNumber(floor, position))\n"
        "    ? `/unit/views/${aptNumber(floor, position)}.jpg`\n"
        "    : null\n\n"
        "// Floors (ascending) where the given svg position has a panorama.\n"
        "export const floorsForPosition = (position) =>\n"
        "  STARGAZE_VIEW_APTS.filter((a) => a % 100 === position).map((a) =>\n"
        "    Math.floor(a / 100),\n"
        "  )\n"
    )
    os.makedirs(os.path.dirname(MANIFEST), exist_ok=True)
    with open(MANIFEST, "w") as f:
        f.write(body)


if __name__ == "__main__":
    main()
